# API
spring:

  # DATABASE
  datasource:
    url: ${DB_URL}
    driver-class-name: ${DRIVER_CLASS_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: ${DATABASE_PLATFORM}
    properties:
      hibernate:
        format_sql: true

# APPLICATION
app:
  path-upload-images-employees: ${UPLOAD_PATH_EMPLOYEE}
  path-upload-files-pdf-reports-sales: ${UPLOAD_PATH_FILES_PDF_REPORTS_SALES}
  path-upload-images-products: ${UPLOAD_PATH_PRODUCTS}