# API
spring:

  # DATABASE
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/db_supermarket_inventory}
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  # JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true

# APPLICATION
app:
  path-upload-images-employees: ${UPLOAD_PATH_EMPLOYEE:uploads/employees}
  path-upload-files-pdf-reports-sales: ${UPLOAD_PATH_FILES_PDF_REPORTS_SALES:uploads/reports/sales}